export const GET_CUSTOMERS_LIST = "GET_CUSTOMERS_LIST";
export const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL";
export const NULLIFY_CUSTOMER_DETAIL = "NULLIFY_CUSTOMER_DETAIL";
export const GET_CUSTOMER_QUOTES = "GET_CUSTOMER_QUOTES";
export const GET_CUSTOMERS_REPORTS = "GET_CUSTOMERS_REPORTS";
export const NULLIFY_CUSTOMER_QUOTES = "NULLIFY_CUSTOMER_QUOTES";
export const NULLIFY_CUSTOMER_REPORTS = "NULLIFY_CUSTOMER_REPORTS";

