export const GET_QUOTES_LIST = "GET_QUOTES_LIST";
export const GET_QUOTE_DETAIL = "GET_QUOTE_DETAIL";
export const NULLIFY_CURRENT_QUOTE = "NULLIFY_CURRENT_QUOTE";
export const GET_PROPERTY_OPTIONS = "GET_PROPERTY_OPTIONS";
export const ADD_NEW_QUOTE = "ADD_NEW_QUOTE";
export const FILTER_QUOTE_LIST = "FILTER_QUOTE_LIST";
