export const GET_STAFF_LIST = "GET_STAFF_LIST";
export const ADD_NEW_STAFF = "ADD_NEW_STAFF";
export const EDIT_STAFF_DETAILS = "EDIT_STAFF_DETAILS";
export const DELETE_STAFF = "DELETE_STAFF";
export const STAFF_STATUS_CHANGE = "STAFF_STATUS_CHANGE";
export const BULK_DELETE_SUPPORT_STAFF = "BULK_DELETE_SUPPORT_STAFF";
